# Generated by Django 2.2.3 on 2019-07-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('protein_id', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_value', models.FloatField()),
                ('protein_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_one', to='TSR3DSystem.Hierarchy')),
                ('protein_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_two', to='TSR3DSystem.Hierarchy')),
            ],
        ),
        migrations.CreateModel(
            name='AllProteins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_key', models.IntegerField()),
                ('key_occurrence', models.IntegerField(null=True)),
                ('aacd0', models.CharField(max_length=3)),
                ('position0', models.IntegerField()),
                ('aacd1', models.CharField(max_length=3)),
                ('position1', models.IntegerField()),
                ('aacd2', models.CharField(max_length=3)),
                ('position2', models.IntegerField()),
                ('classT1', models.IntegerField()),
                ('theta', models.FloatField()),
                ('classL1', models.IntegerField()),
                ('maxDist', models.FloatField()),
                ('x0', models.FloatField()),
                ('y0', models.FloatField()),
                ('z0', models.FloatField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('z1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('z2', models.FloatField()),
                ('protein_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='TSR3DSystem.Hierarchy')),
            ],
        ),
    ]
